# Generated by Django 4.2.3 on 2023-09-08 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_remove_auctionlisting_list_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='categories', to='auctions.auctionlisting'),
        ),
        migrations.AddField(
            model_name='user',
            name='listings',
            field=models.ManyToManyField(blank=True, related_name='listings', to='auctions.auctionlisting'),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='image',
            field=models.URLField(),
        ),
    ]
