# Generated by Django 4.2.3 on 2023-09-09 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_category_categories_user_listings_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='first',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='user',
            name='listings',
            field=models.ManyToManyField(blank=True, related_name='listingsmuch', to='auctions.auctionlisting'),
        ),
    ]
