# Generated by Django 4.2.3 on 2023-09-13 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_rename_first_watchlist_user_alter_user_listings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='user_made',
            new_name='user',
        ),
    ]
